import { useState, useRef } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Typography,
  Alert,
  Paper,
  alpha,
} from '@mui/material';
import UploadFileIcon from '@mui/icons-material/UploadFile';
import { useResume } from '../../hooks/useResume.js';
import { useLocale } from '../../hooks/useLocale.js';
import { useSnackbar } from 'notistack';
import { parseAndValidateResumeJson } from '../../utils/jsonResume.js';

/**
 * @file ImportJsonModal.jsx
 * @description Dialog allowing users to upload a previously exported OzCraft JSON file,
 * validating its structure and immediately populating the builder and preview.
 *
 * @param {object} props
 * @param {boolean} props.open - Modal visibility state
 * @param {() => void} props.onClose - Modal close handler
 */
export function ImportJsonModal({ open, onClose }) {
  const { loadResumeData } = useResume();
  const { t } = useLocale();
  const { enqueueSnackbar } = useSnackbar();

  const [dragOver, setDragOver] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const fileInputRef = useRef(null);

  const processFile = (file) => {
    if (!file) return;
    setErrorMsg('');

    if (!file.name.endsWith('.json')) {
      setErrorMsg('Please select a valid .json file.');
      return;
    }

    const reader = new FileReader();
    reader.onload = (e) => {
      const content = e.target.result;
      const result = parseAndValidateResumeJson(content);

      if (result.success) {
        try {
          loadResumeData(result.data);
          enqueueSnackbar(t('import.success'), { variant: 'success' });
          onClose();
        } catch (err) {
          setErrorMsg(err.message || t('import.error'));
        }
      } else {
        setErrorMsg(result.error || t('import.error'));
      }
    };
    reader.onerror = () => {
      setErrorMsg('Failed to read file from disk.');
    };
    reader.readAsText(file);
  };

  const handleDrop = (e) => {
    e.preventDefault();
    setDragOver(false);
    const file = e.dataTransfer.files?.[0];
    processFile(file);
  };

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="sm"
      fullWidth
      PaperProps={{ sx: { borderRadius: 3, p: 1 } }}
    >
      <DialogTitle sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
        <UploadFileIcon color="primary" />
        <Typography variant="h6" sx={{ fontWeight: 700 }}>
          {t('import.title')}
        </Typography>
      </DialogTitle>

      <DialogContent dividers sx={{ borderLeft: 'none', borderRight: 'none' }}>
        <Typography variant="body2" sx={{ color: 'text.secondary', mb: 2 }}>
          {t('import.desc')}
        </Typography>

        {errorMsg && (
          <Alert severity="error" sx={{ mb: 2, borderRadius: 2 }}>
            {errorMsg}
          </Alert>
        )}

        <Paper
          variant="outlined"
          onDragOver={(e) => {
            e.preventDefault();
            setDragOver(true);
          }}
          onDragLeave={() => setDragOver(false)}
          onDrop={handleDrop}
          onClick={() => fileInputRef.current?.click()}
          sx={{
            p: 4,
            textAlign: 'center',
            cursor: 'pointer',
            borderRadius: 2.5,
            borderStyle: 'dashed',
            borderWidth: 2,
            borderColor: dragOver ? 'primary.main' : 'divider',
            backgroundColor: (theme) =>
              dragOver ? alpha(theme.palette.primary.main, 0.05) : 'background.default',
            transition: 'all 0.2s ease',
            '&:hover': {
              borderColor: 'primary.main',
            },
          }}
        >
          <input
            type="file"
            ref={fileInputRef}
            accept=".json,application/json"
            style={{ display: 'none' }}
            onChange={(e) => processFile(e.target.files?.[0])}
          />
          <UploadFileIcon sx={{ fontSize: 44, color: 'text.secondary', mb: 1 }} />
          <Typography variant="subtitle2" sx={{ fontWeight: 600 }}>
            {t('import.dragDrop')}
          </Typography>
          <Typography variant="caption" sx={{ color: 'text.secondary' }}>
            Supports .json files generated by OzCraft
          </Typography>
        </Paper>
      </DialogContent>

      <DialogActions sx={{ p: 2 }}>
        <Button onClick={onClose} color="inherit">
          {t('ai.discard')}
        </Button>
      </DialogActions>
    </Dialog>
  );
}
